#64 Fix duration chart: If there are multiple todos for one day, show the sum (#66)
* First attempt to fix, calculating total duration of all todos for a date.

But now raises error: AttributeError: 'NoneType' object has no attribute 'total_seconds'

* Add comment

* Add missing check if duration is defined