#13 Split code into multiple files (#49)
* [WIP] Create separate models module, import db from app module. __init__.py of app module initializes app and db.
Error: No module named 'models'

* Fixed imports: relative module paths need to begin with '.'

* Remove useless imports, add missing requirement

* Split model classes into separate files

* Extract get_todo_lists logic into TodoList class

* Extract setting logic into Setting class

* Extract get_todo_list logic into TodoList and Todo

* Remove unused old create_order_by_clause methods, simplify name, make them private

* Use Setting.set method for todo lists as well, remove unused code

* Extract rest of TodoList logic into TodoList class

* Extract rest of Todo logic into Todo class

* Remove unused import

* Rename 'update_todo' to 'toggle_todo_completed'

* Extract todo_list_table_row.html

* Make all imports use relative paths and remove unused imports